In [28]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
a.shape

(2, 7)

In [41]:
# Get specific element [r, c]
a[1, -3]

12

In [40]:
a[:, 2:5]

array([[ 3,  4,  5],
       [10, 11, 12]])